name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v3
    - name: Pull Docker image from Docker Hub
      run: |
        docker pull ${{ secrets.DOCKERHUB_USERNAME }}/inkbook-api:${{ github.sha }}
    - name: Deploy to Environment
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/inkbook-api:${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "Deploying to production"
          # production deploy command here
        elif [[ "${GITHUB_REF}" == "refs/heads/develop" ]]; then
          echo "Deploying to staging"
          # staging deploy command here
        else
          echo "Not a deployable branch: $GITHUB_REF"
        fi
    - name: Notify Deployment Status
      if: always()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: deployments
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: Deployment Status
        SLACK_MESSAGE: 'Deployment to ${{ github.ref }} ${{ job.status }}'
        SLACK_FOOTER: 'InkBook API' 